spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.1.163/sell?characterEncoding=utf-8&useSSl=false
  jpa:
    show-sql: true
#    如果返回到前端的对象是null的话，则不显示
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379
    database: 5


wechat:
  mpAppId: wx71cdd640e05fd544
  mpAppSecret: 33fd7e155f3784dd8216375085296101
  openAppId: wx6ad144e54af67d87
  openAppSecret: 91a2ff6d38a2bbccfb7e9f9079108e2e
  mchId: 1488817722
  mchKey: wxpay00001488817722Local12y34560
  keyPath: classpath:wxpay_server_cert.p12
  notifyUrl: http://sell.natapp4.cc/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://huadong.natapp1.cc
  wechatOpenAuthorize: http://huadong.natapp1.cc
  sell: http://huadong.natapp1.cc
server:
  servlet:
    context-path: /sell
